### ISSUE TITLE
Cannot load .vol file created from .stl

### ISSUE THREAD

**Issue by Alex-Vasile** [NGSolve/ngsolve#41] opened 2022-01-12 19:38 UTC
Note: because of GitHub restriction, you will have to rename `led.txt` to `led.stl` and `reproduce.txt` to `reproduce.py`.

I have the following [.stl file](https://github.com/NGSolve/ngsolve/files/7857222/led.txt) which converted to .vol properly in the past using the attached [script](https://github.com/NGSolve/ngsolve/files/7857224/reproduce.txt).

When I try to run the script it fails with the following error:
```
    volmesh.Load('led.vol')
IndexError: basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 7)
```

However if I run the Netgen GUI, I am able to import the created .vol file and view it without any error.

Ubuntu 21.10
Python 3.9.7
NGSolve-6.2.2105

**Comment by ChrLackner** [comment] 2022-04-25 11:03
Hi,
I cannot reproduce this issue with the newest version. I think it is fixed in the latest master. Please reopen if not.

**Closed by ChrLackner** 2022-04-25 11:03 UTC
